---
label: Layout-Default
hide_body: true
fields:
- name: page
  type: include
  config: {}
  template: page
  label: Page Details
- name: sections
  type: blocks
  label: Sections
  template_types:
  - hero
  - quick-links
  - text-area
  - purple-carousel
  - card-with-image
  - history
  - green-carousel
  - testimonial
  config:
    min: 
    max: 
pages:
- pages/get-involved/this-will-work-s.md
