---
label: Default
hide_body: true
fields:
- name: page
  type: include
  config: {}
  template: page
  label: Page Details
- name: page_sections
  type: blocks
  label: Page Sections
  template_types:
  - hero
  - quick-links
  config:
    min: 
    max: 
