---
label: Default
hide_body: false
fields:
- name: hero
  type: include
  config: {}
  template: hero
  label: Hero
- name: page
  type: include
  config: {}
  template: page
  label: page
- name: quick_links
  type: include
  config: {}
  template: quick-links
  label: Quick Links
